FROM debian:11-slim as build
RUN apt update && \
    apt install -y python3 \
    python3-pip 
WORKDIR /app
COPY . .
RUN pip3 install wheel && pip wheel --wheel-dir=/app/wheels


FROM python:3.8-alpine
COPY --from=bluid /app /app
WORKDIR /app
RUN pip install --no-index --find-links=/app/wheels -r requirements.txt
RUN apk add --update \
    apache2 libapache2-mod-wsgi-py3
COPY /flask-contacts.conf /etc/apache2/sites-available/flask-contacts.conf
RUN a2ensite flask-contacts \
    a2enmod headers
EXPOSE 80
CMD /usr/sbin/apache2ctl -D FOREGROUND

